### ISSUE TITLE
Session.init hangs on unauthorized vhost use

### ISSUE THREAD

**Issue by divarvel** [Antti/rust-amqp#7] opened 2015-07-31 12:49 UTC
See #4

**Comment by Antti** [comment] 2015-07-31 13:05
The problem is that we're not notifying session that the connection broke.
One of the solutions may be in sending `AMQPResult<Frame>` through channel instead of Frame, so we can also send errors and handle them in upper in the stack.

**Comment by Antti** [comment] 2015-08-18 13:42
Should be fixed now.
When reading_loop spots IO error, it will propagate that error to all channels, hoping they will handle it.

**Comment by divarvel** [comment] 2015-08-18 13:51
Great, thanks!
ᐧ

Regards,
Clément Delafargue

PGP Fingerprint : 5311 A6C4 8416 5378 3019  B977 FFB4 9299 EAE0 ED53

**Closed** 2015-08-24 13:12 UTC
